package Enums;

public enum PetAbilityProcType
{
    PET_BATTLE_EVENT_ON_APPLY,
    PET_BATTLE_EVENT_ON_DAMAGE_TAKEN,
    PET_BATTLE_EVENT_ON_DAMAGE_DEALT,
    PET_BATTLE_EVENT_ON_HEAL_TAKEN,
    PET_BATTLE_EVENT_ON_HEAL_DEALT,
    PET_BATTLE_EVENT_ON_AURA_REMOVED,
    PET_BATTLE_EVENT_ON_ROUND_START,
    PET_BATTLE_EVENT_ON_ROUND_END,
    PET_BATTLE_EVENT_ON_TURN,
    PET_BATTLE_EVENT_ON_ABILITY,
    PET_BATTLE_EVENT_ON_SWAP_IN,
    PET_BATTLE_EVENT_ON_SWAP_OUT,
    PET_BATTLE_EVENT_FEIGN_DEATH; // only Feign Death
}
